# Generated by Django 5.2.1 on 2025-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_question_correct_answer_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube video URL to embed.', null=True),
        ),
    ]
